'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {spawnSync}=require('node:child_process');
const {CodexRuntimeBroker}=require('../../codex/CodexRuntimeBroker');const {FakeAppServer}=require('../../codex/testing/FakeAppServer');
const DIFF=`diff --git a/a.txt b/a.txt\nindex 3367afd..3e75765 100644\n--- a/a.txt\n+++ b/a.txt\n@@ -1 +1 @@\n-old\n+new\n`;
function git(cwd,args){const r=spawnSync('git',['-C',cwd,...args],{encoding:'utf8',shell:false});if(r.status)throw new Error(r.stderr);return r.stdout.trim();}
function fixture(){const base=fs.mkdtempSync(path.join(os.tmpdir(),'papers-broker-patch-'));const repo=path.join(base,'repo');const wt=path.join(base,'wt');fs.mkdirSync(repo);git(repo,['init']);git(repo,['config','user.email','papers@example.invalid']);git(repo,['config','user.name','Papers Test']);fs.writeFileSync(path.join(repo,'a.txt'),'old\n');git(repo,['add','.']);git(repo,['commit','-m','base']);git(repo,['worktree','add','-b','owned-patch',wt]);return{base,repo,wt,cleanup(){try{git(repo,['worktree','remove','--force',wt]);}catch{}fs.rmSync(base,{recursive:true,force:true});}};}
function makeBroker(f,mode='decline') {const userDataDir=fs.mkdtempSync(path.join(os.tmpdir(),'papers-home-'));let fake;const script={codexHome:path.join(userDataDir,'codex-home'),afterTurnStart(emit){emit.notification({jsonrpc:'2.0',method:'turn/started',params:{turn:{id:'turn1'}}});emit.notification({jsonrpc:'2.0',method:'item/started',params:{item:{id:'item1',type:'fileChange',status:'inProgress',rawDiff:DIFF}}});emit.serverRequest({jsonrpc:'2.0',method:'item/fileChange/requestApproval',params:{itemId:'item1',threadId:'th_fake_1',turnId:'turn1',changes:[{path:'a.txt'}]}});},onRespond(_id,payload,emit){if(payload.decision==='decline'&&mode!=='silent'){emit.notification({jsonrpc:'2.0',method:'item/completed',params:{item:{id:'item1',type:'fileChange',status:mode==='conflict'?'completed':'declined'}}});}}};const broker=new CodexRuntimeBroker({userDataDir,env:{},transportFactory:()=>{fake=new FakeAppServer(script);return fake;}});return{broker,getFake:()=>fake,cleanup:()=>fs.rmSync(userDataDir,{recursive:true,force:true})};}
async function waitFor(fn){for(let i=0;i<100;i++){if(fn())return;await new Promise(r=>setTimeout(r,5));}throw new Error('timeout');}
test('Fake App Server fileChange is captured once, declined first, then applied by Papers with truthful receipt',async()=>{const f=fixture();const b=makeBroker(f);const events=[];b.broker.on('patch',e=>events.push(e));try{await b.broker.start();await b.broker.startTask({workspace:f.wt,instruction:'change a'});await waitFor(()=>b.broker.listPatchProposals().length===1);const p=b.broker.listPatchProposals()[0];assert.match(fs.readFileSync(path.join(f.wt,'a.txt'),'utf8'),/^old\r?\n$/);const receipt=await b.broker.applyPatchProposal(p.proposalId);assert.match(fs.readFileSync(path.join(f.wt,'a.txt'),'utf8'),/^new\r?\n$/);assert.equal(b.getFake().decisions[0].payload.decision,'decline');assert.equal(receipt.providerDecision,'decline');assert.equal(receipt.outcome,'applied-by-papers');assert.equal(b.broker.listPatchProposals().length,1);assert.deepEqual(git(f.wt,['status','--porcelain']).split(/\r?\n/),['M a.txt']);assert.ok(events.some(e=>e.type==='providerDeclineConfirmed'));}finally{await b.broker.stop();b.cleanup();f.cleanup();}});
test('Fake App Server denial failure prevents Papers mutation',async()=>{const f=fixture();const b=makeBroker(f,'silent');try{await b.broker.start();await b.broker.startTask({workspace:f.wt,instruction:'change a'});await waitFor(()=>b.broker.listPatchProposals().length===1);b.broker.patchController.declineTimeoutMs=20;await assert.rejects(()=>b.broker.applyPatchProposal(b.broker.listPatchProposals()[0].proposalId),/not confirmed/);assert.match(fs.readFileSync(path.join(f.wt,'a.txt'),'utf8'),/^old\r?\n$/);}finally{await b.broker.stop();b.cleanup();f.cleanup();}});
