'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {spawnSync}=require('node:child_process');
const {parseProviderMessageProposal}=require('../../patch/ProviderMessageProposalParser');
const {PapersPatchController}=require('../../patch/PapersPatchController');
const {CodexRuntimeBroker}=require('../../codex/CodexRuntimeBroker');
const {FakeAppServer}=require('../../codex/testing/FakeAppServer');
const {validateStartTask}=require('../../codex/protocol/validators');
const {isTruthfulReceipt,receiptRows,applyResolution}=require('../../ui/patch-receipt-view');

const NONCE='a'.repeat(32);
const DIFF=`diff --git a/a.txt b/a.txt\nindex 7898192..6178079 100644\n--- a/a.txt\n+++ b/a.txt\n@@ -1 +1 @@\n-a\n+b\n`;
const GOOD=JSON.stringify({schema:'papers.patch-proposal.v1',nonce:NONCE,summary:'change a.txt',diff:DIFF});
const parse=(text,nonce)=>parseProviderMessageProposal(text,{nonce:nonce||NONCE});
const rejects=(text,category)=>{try{parse(text);assert.fail('should reject');}catch(err){if(err.code!=='PATCH_INVALID')throw err;assert.equal(err.code,'PATCH_INVALID');if(category)assert.equal(err.category,category);}};

// --- parser -----------------------------------------------------------------
test('raw exact JSON accepted',()=>{const r=parse(GOOD);assert.equal(r.diff,DIFF);assert.equal(r.summary,'change a.txt');});
test('single exact json fence accepted',()=>{const r=parse('```json\n'+GOOD+'\n```');assert.equal(r.diff,DIFF);});
test('prose before JSON rejected',()=>rejects('Here is the proposal:\n'+GOOD,'unexpected response format'));
test('prose after JSON rejected',()=>rejects(GOOD+'\nDone!','unexpected response format'));
test('multiple fences rejected',()=>rejects('```json\n'+GOOD+'\n```\n```json\n'+GOOD+'\n```','unexpected response format'));
test('non-json fence rejected',()=>rejects('```patch\n'+GOOD+'\n```','unexpected response format'));
test('apply_patch envelope rejected',()=>rejects('*** Begin Patch\n*** Update File: a.txt\n@@\n-a\n+b\n*** End Patch','unexpected response format'));
test('markdown diff fence rejected',()=>rejects('```diff\n-a\n+b\n```','unexpected response format'));
test('malformed JSON rejected',()=>rejects('{"schema": "papers.patch-proposal.v1", nope}','invalid JSON'));
test('array rejected',()=>rejects('['+GOOD+']','unexpected response format'));
test('duplicate key rejected',()=>rejects('{"schema":"papers.patch-proposal.v1","schema":"papers.patch-proposal.v1","nonce":"'+NONCE+'","summary":"s","diff":"d"}','wrong schema'));
test('unknown field rejected',()=>rejects(JSON.stringify({schema:'papers.patch-proposal.v1',nonce:NONCE,summary:'s',diff:DIFF,extra:1}),'wrong schema'));
test('missing schema rejected',()=>rejects(JSON.stringify({nonce:NONCE,summary:'s',diff:DIFF}),'wrong schema'));
test('wrong schema rejected',()=>rejects(JSON.stringify({schema:'papers.patch-proposal.v2',nonce:NONCE,summary:'s',diff:DIFF}),'wrong schema'));
test('wrong nonce rejected',()=>rejects(JSON.stringify({schema:'papers.patch-proposal.v1',nonce:'b'.repeat(32),summary:'s',diff:DIFF}),'wrong nonce'));
test('empty diff rejected',()=>rejects(JSON.stringify({schema:'papers.patch-proposal.v1',nonce:NONCE,summary:'s',diff:''}),'invalid diff'));
test('oversized diff rejected',()=>rejects(JSON.stringify({schema:'papers.patch-proposal.v1',nonce:NONCE,summary:'s',diff:'x'.repeat(262145)}),'invalid diff'));
test('NUL rejected',()=>rejects(GOOD+'\0','unexpected response format'));
test('oversized summary rejected',()=>rejects(JSON.stringify({schema:'papers.patch-proposal.v1',nonce:NONCE,summary:'s'.repeat(301),diff:DIFF}),'wrong schema'));
test('apply_patch envelope inside diff field rejected',()=>rejects(JSON.stringify({schema:'papers.patch-proposal.v1',nonce:NONCE,summary:'s',diff:'*** Begin Patch\n*** End Patch'}),'invalid diff'));

test('diff without trailing newline fails closed at validation, not at git apply',()=>{const {validateUnifiedDiff}=require('../../patch/PatchProposalValidator');assert.throws(()=>validateUnifiedDiff(DIFF.replace(/\n$/,'')),/trailing newline/);assert.doesNotThrow(()=>validateUnifiedDiff(DIFF));});
test('contract requires the trailing-newline rule',()=>{const {buildProposalOnlyInstruction}=require('../../patch/ProviderMessageProposalParser');assert.match(buildProposalOnlyInstruction(NONCE,'x'),/MUST end with a final newline/);});
test('contract instructs git-format diff headers with example',()=>{const {buildProposalOnlyInstruction}=require('../../patch/ProviderMessageProposalParser');const s=buildProposalOnlyInstruction(NONCE,'do the thing');assert.match(s,/diff --git a\/<path> b\/<path>/);assert.match(s,/diff --git a\/example\.txt b\/example\.txt/);assert.match(s,/Creator instruction:\ndo the thing$/);assert.ok(s.includes(NONCE));});

// --- terminal-LF transport canonicalization ----------------------------------
const sha256=(s)=>require('node:crypto').createHash('sha256').update(s,'utf8').digest('hex');
const NOLF=DIFF.replace(/\n$/,'');
const GOOD_NOLF=JSON.stringify({schema:'papers.patch-proposal.v1',nonce:NONCE,summary:'change a.txt',diff:NOLF});
test('valid diff with terminal LF is unchanged',()=>{const r=parse(GOOD);assert.equal(r.diff,DIFF);assert.equal(r.terminalLfAppended,false);assert.equal(r.rawProviderDiffSHA256,sha256(DIFF));});
test('missing terminal LF receives exactly one LF',()=>{const r=parse(GOOD_NOLF);assert.equal(r.diff,DIFF);assert.equal(r.terminalLfAppended,true);});
test('existing trailing LFs are not expanded',()=>{const two=DIFF+'\n';const r=parse(JSON.stringify({schema:'papers.patch-proposal.v1',nonce:NONCE,summary:'s',diff:two}));assert.equal(r.diff,two);assert.equal(r.terminalLfAppended,false);});
test('raw and canonical hashes differ when LF is appended',()=>{const r=parse(GOOD_NOLF);assert.equal(r.rawProviderDiffSHA256,sha256(NOLF));assert.notEqual(r.rawProviderDiffSHA256,sha256(r.diff));});
test('canonical patch hash matches applied bytes and receipt is truthful about LF',async()=>{const f=worktrees();try{const c=new PapersPatchController({approvals:null});const parsed=parse(GOOD_NOLF);const p=c.captureProviderMessage({threadId:'th',turnId:'tu',messageItemId:'m1',worktreeRoot:f.linked,repositoryRoot:f.linked,rawDiff:parsed.diff,summary:parsed.summary,terminalLfAppended:parsed.terminalLfAppended,rawProviderDiffSHA256:parsed.rawProviderDiffSHA256,turnTerminalConfirmed:true});assert.equal(p.terminalLfAppended,true);const r=await c.apply(p.proposalId);assert.equal(r.patchSHA256,sha256(DIFF));assert.equal(r.terminalLfAppended,true);assert.equal(r.rawProviderDiffSHA256,sha256(NOLF));assert.notEqual(r.patchSHA256,r.rawProviderDiffSHA256);const rows=receiptRows(r);assert.equal(Object.fromEntries(rows)['Transport normalization'],'Added required terminal line ending');}finally{f.cleanup();}});
test('receipt without LF normalization shows no normalization row',async()=>{const f=worktrees();try{const{c,p}=msgController(f);const r=await c.apply(p.proposalId);assert.equal(r.terminalLfAppended,false);assert.equal(Object.fromEntries(receiptRows(r))['Transport normalization'],undefined);}finally{f.cleanup();}});
test('missing diff --git header remains rejected after canonicalization',()=>{const f=worktrees();try{const c=new PapersPatchController({approvals:null});const headerless=parse(JSON.stringify({schema:'papers.patch-proposal.v1',nonce:NONCE,summary:'s',diff:'--- a/a.txt\n+++ b/a.txt\n@@ -1 +1 @@\n-a\n+b'}));assert.equal(headerless.terminalLfAppended,true);assert.throws(()=>c.captureProviderMessage({threadId:'t',turnId:'u',messageItemId:'m',worktreeRoot:f.linked,repositoryRoot:f.linked,rawDiff:headerless.diff,turnTerminalConfirmed:true}));}finally{f.cleanup();}});
test('missing file headers and malformed hunks remain rejected',()=>{const {validateUnifiedDiff}=require('../../patch/PatchProposalValidator');assert.throws(()=>validateUnifiedDiff('diff --git a/a.txt b/a.txt\n@@ -1 +1 @@\n-a\n+b\n'));assert.throws(()=>validateUnifiedDiff('diff --git a/a.txt b/a.txt\n--- a/a.txt\n+++ b/a.txt\n@@ -x +y @@\n-a\n+b\n'));});
test('no normalization occurs outside provider-message mode',()=>{const f=worktrees();try{const c=new PapersPatchController({approvals:{submitDecision(){}}});assert.throws(()=>c.capture({threadId:'t',turnId:'u',itemId:'i',approvalRequestId:1,approvalId:'a',worktreeRoot:f.linked,repositoryRoot:f.linked,rawDiff:NOLF}),/trailing newline/);}finally{f.cleanup();}});

// --- fixture helpers ----------------------------------------------------------
function git(cwd,args){const r=spawnSync('git',['-C',cwd,...args],{encoding:'utf8',shell:false});if(r.status)throw new Error(r.stderr);return r.stdout.trim();}
function worktrees(){const base=fs.mkdtempSync(path.join(os.tmpdir(),'papers-msg-'));const repo=path.join(base,'repo');const linked=path.join(base,'linked');fs.mkdirSync(repo);git(repo,['init']);git(repo,['config','user.email','papers@example.invalid']);git(repo,['config','user.name','Papers Test']);git(repo,['config','core.autocrlf','false']);fs.writeFileSync(path.join(repo,'a.txt'),'a\n');git(repo,['add','.']);git(repo,['commit','-m','base']);git(repo,['worktree','add','-b','creator-task',linked]);return{base,repo,linked,cleanup(){try{git(repo,['worktree','remove','--force',linked]);}catch{}fs.rmSync(base,{recursive:true,force:true});}};}
function msgController(f,opts={}){const c=new PapersPatchController({approvals:null,...opts});const p=c.captureProviderMessage({threadId:'th',turnId:'tu',messageItemId:'m1',worktreeRoot:f.linked,repositoryRoot:f.linked,rawDiff:DIFF,summary:'s',provider:'codex',model:'gpt-5.4-mini',turnTerminalConfirmed:true});return{c,p};}

// --- controller: invalid/unsafe diffs, staleness, drift ----------------------
test('invalid unified diff rejected at message capture',()=>{const f=worktrees();try{const c=new PapersPatchController({approvals:null});assert.throws(()=>c.captureProviderMessage({threadId:'t',turnId:'u',messageItemId:'m',worktreeRoot:f.linked,repositoryRoot:f.linked,rawDiff:'not a diff',turnTerminalConfirmed:true}));}finally{f.cleanup();}});
test('unsafe path rejected through existing validator',()=>{const f=worktrees();try{const c=new PapersPatchController({approvals:null});assert.throws(()=>c.captureProviderMessage({threadId:'t',turnId:'u',messageItemId:'m',worktreeRoot:f.linked,repositoryRoot:f.linked,rawDiff:DIFF.replaceAll('a.txt','../a.txt'),turnTerminalConfirmed:true}));}finally{f.cleanup();}});
test('stale message proposal rejected',async()=>{const f=worktrees();try{const{c,p}=msgController(f,{staleMs:1});await new Promise(r=>setTimeout(r,5));await assert.rejects(()=>c.apply(p.proposalId),/stale/i);}finally{f.cleanup();}});
test('worktree drift rejects message apply',async()=>{const f=worktrees();try{const{c,p}=msgController(f);fs.writeFileSync(path.join(f.linked,'a.txt'),'drift\n');await assert.rejects(()=>c.apply(p.proposalId),/clean|changed|drift/i);assert.match(fs.readFileSync(path.join(f.linked,'a.txt'),'utf8'),/^drift\r?\n$/);}finally{f.cleanup();}});
test('unconfirmed turn cannot apply',async()=>{const f=worktrees();try{const c=new PapersPatchController({approvals:null});const p=c.captureProviderMessage({threadId:'t',turnId:'u',messageItemId:'m',worktreeRoot:f.linked,repositoryRoot:f.linked,rawDiff:DIFF,turnTerminalConfirmed:false});await assert.rejects(()=>c.apply(p.proposalId),/turn completion/i);assert.match(fs.readFileSync(path.join(f.linked,'a.txt'),'utf8'),/^a\r?\n$/);}finally{f.cleanup();}});
test('message apply produces not-applicable receipt without approval coordinator',async()=>{const f=worktrees();try{const{c,p}=msgController(f);const r=await c.apply(p.proposalId);assert.equal(r.proposalSource,'provider-message-json');assert.equal(r.providerDecision,'not-applicable');assert.equal(r.providerActionRequested,false);assert.equal(r.providerTerminalStatus,'completed');assert.equal(r.turnTerminalConfirmed,true);assert.equal(r.outcome,'applied-by-papers');assert.equal(r.messageItemId,'m1');assert.ok(r.patchSHA256&&r.resultingDiffSHA256);assert.doesNotMatch(JSON.stringify(r),/nonce/i);assert.match(fs.readFileSync(path.join(f.linked,'a.txt'),'utf8'),/^b\r?\n$/);assert.ok(isTruthfulReceipt(r));}finally{f.cleanup();}});
test('discard resolves message proposal without provider decision',async()=>{const f=worktrees();try{const{c,p}=msgController(f);assert.deepEqual(c.deny(p.proposalId),{resolution:'discarded'});await assert.rejects(()=>c.apply(p.proposalId),/already decided/);}finally{f.cleanup();}});
test('message receipt claiming decline is untruthful; UI rows never say denial',async()=>{const f=worktrees();try{const{c,p}=msgController(f);const r=await c.apply(p.proposalId);const rows=receiptRows(r);const flat=JSON.stringify(rows);assert.doesNotMatch(flat,/denial|decline\b/i);assert.equal(Object.fromEntries(rows)['Provider decision'],'not-applicable');assert.equal(isTruthfulReceipt({...r,providerDecision:'decline'}),false);assert.equal(isTruthfulReceipt({...r,providerActionRequested:true}),false);assert.equal(applyResolution({ok:true,value:{...r,providerDecision:'decline'}}).state,'failed');assert.equal(applyResolution({ok:true}).state,'failed');}finally{f.cleanup();}});
test('renderer cannot submit diff or nonce',()=>{assert.throws(()=>validateStartTask({workspace:'D:\\w',instruction:'x',requireOffline:false,diff:'d'}),/unknown field/);assert.throws(()=>validateStartTask({workspace:'D:\\w',instruction:'x',requireOffline:false,nonce:'n'}),/unknown field/);});

// --- broker: trusted capture, correlation, precedence -------------------------
function brokerFixture(afterTurnStart){const userDataDir=fs.mkdtempSync(path.join(os.tmpdir(),'papers-msgbrk-'));let nonce=null;const fake=()=>f;let f;const broker=new CodexRuntimeBroker({userDataDir,env:{},authFactory:()=>({getStatus:async()=>({state:'authenticated'}),beginAuthentication:async()=>({state:'authenticating',command:'c'}),logout:async()=>({state:'unauthenticated'})}),transportFactory:()=>{f=new FakeAppServer({codexHome:path.join(userDataDir,'codex-home'),afterTurnStart:(emit,params)=>{const m=/"nonce": "([0-9a-f]{32})"/.exec(params.input[0].text);nonce=m&&m[1];afterTurnStart(emit,()=>nonce);}});return f;}});const events=[];broker.on('patch',(e)=>events.push(e));return{broker,events,getFake:fake,async until(pred,ms=1500){const t0=Date.now();while(Date.now()-t0<ms){if(pred())return true;await new Promise(r=>setTimeout(r,5));}return pred();},cleanup:async()=>{try{await broker.stop();}catch{}fs.rmSync(userDataDir,{recursive:true,force:true});}};}
const TH='th_fake_1',TU='tu1';
function stdTurn(emit){emit.notification({method:'turn/started',params:{threadId:TH,turn:{id:TU}}});}
function finalMsg(emit,nonce,over={}){emit.notification({method:'item/completed',params:{threadId:over.threadId||TH,turnId:over.turnId||TU,item:{type:'agentMessage',id:over.id||'m1',phase:'final_answer',text:over.text||JSON.stringify({schema:'papers.patch-proposal.v1',nonce,summary:'change a.txt',diff:DIFF})}}});}
function completeTurn(emit,status='completed'){emit.notification({method:'turn/completed',params:{threadId:TH,turn:{id:TU,status}}});}

test('duplicate final-message completions deduplicate to one proposal',async()=>{const wt=worktrees();const x=brokerFixture((emit,nonce)=>{stdTurn(emit);finalMsg(emit,nonce());finalMsg(emit,nonce());completeTurn(emit);});try{await x.broker.startTask({workspace:wt.linked,instruction:'change'});await x.until(()=>x.events.some(e=>e.type==='proposal-turn-ended'));const props=x.broker.listPatchProposals();assert.equal(props.length,1);assert.equal(props[0].proposalSource,'provider-message-json');assert.equal(props[0].turnTerminalConfirmed,true);}finally{await x.cleanup();wt.cleanup();}});
test('message from wrong turn rejected',async()=>{const wt=worktrees();const x=brokerFixture((emit,nonce)=>{stdTurn(emit);finalMsg(emit,nonce(),{turnId:'other-turn'});completeTurn(emit);});try{await x.broker.startTask({workspace:wt.linked,instruction:'c'});await x.until(()=>x.events.some(e=>e.type==='proposal-turn-ended'));assert.equal(x.broker.listPatchProposals().length,0);assert.equal(x.events.find(e=>e.type==='proposal-turn-ended').outcome,'no-proposal');}finally{await x.cleanup();wt.cleanup();}});
test('message from wrong thread rejected',async()=>{const wt=worktrees();const x=brokerFixture((emit,nonce)=>{stdTurn(emit);finalMsg(emit,nonce(),{threadId:'other-thread'});completeTurn(emit);});try{await x.broker.startTask({workspace:wt.linked,instruction:'c'});await x.until(()=>x.events.some(e=>e.type==='proposal-turn-ended'));assert.equal(x.broker.listPatchProposals().length,0);}finally{await x.cleanup();wt.cleanup();}});
test('proposal unavailable before turn completion',async()=>{const wt=worktrees();const x=brokerFixture((emit,nonce)=>{stdTurn(emit);finalMsg(emit,nonce());});try{await x.broker.startTask({workspace:wt.linked,instruction:'c'});await new Promise(r=>setTimeout(r,50));assert.equal(x.broker.listPatchProposals().length,0);assert.equal(x.events.some(e=>e.type==='patch-proposal-captured'),false);}finally{await x.cleanup();wt.cleanup();}});
test('wrong-nonce final message is rejected with category',async()=>{const wt=worktrees();const x=brokerFixture((emit)=>{stdTurn(emit);finalMsg(emit,'f'.repeat(32));completeTurn(emit);});try{await x.broker.startTask({workspace:wt.linked,instruction:'c'});await x.until(()=>x.events.some(e=>e.type==='proposal-turn-ended'));const ev=x.events.find(e=>e.type==='proposal-turn-ended');assert.equal(ev.outcome,'rejected');assert.equal(ev.category,'wrong nonce');assert.equal(x.broker.listPatchProposals().length,0);}finally{await x.cleanup();wt.cleanup();}});
test('structured fileChange takes precedence over message proposal',async()=>{const wt=worktrees();const x=brokerFixture((emit)=>{stdTurn(emit);emit.notification({method:'item/started',params:{item:{id:'fc1',type:'fileChange',rawDiff:DIFF}}});emit.serverRequest({method:'item/fileChange/requestApproval',params:{itemId:'fc1',threadId:TH,turnId:TU}});completeTurn(emit);});try{await x.broker.startTask({workspace:wt.linked,instruction:'c'});await x.until(()=>x.events.some(e=>e.type==='proposal-turn-ended'));const props=x.broker.listPatchProposals();assert.equal(props.length,1);assert.equal(props[0].proposalSource,'provider-filechange');assert.equal(props[0].providerDecisionRequired,true);assert.equal(x.events.find(e=>e.type==='proposal-turn-ended').outcome,'structured');}finally{await x.cleanup();wt.cleanup();}});
test('command approval suppresses message proposal',async()=>{const wt=worktrees();const x=brokerFixture((emit,nonce)=>{stdTurn(emit);emit.serverRequest({method:'item/commandExecution/requestApproval',params:{itemId:'cmd1',command:'echo hi',cwd:wt.linked,threadId:TH,turnId:TU}});finalMsg(emit,nonce());completeTurn(emit);});try{await x.broker.startTask({workspace:wt.linked,instruction:'c'});await x.until(()=>x.events.some(e=>e.type==='proposal-turn-ended'));const ev=x.events.find(e=>e.type==='proposal-turn-ended');assert.equal(ev.outcome,'command-suppressed');assert.equal(x.broker.listPatchProposals().filter(p=>p.proposalSource==='provider-message-json').length,0);}finally{await x.cleanup();wt.cleanup();}});
test('structured plus message in one turn is a conflict; nothing applies',async()=>{const wt=worktrees();const x=brokerFixture((emit,nonce)=>{stdTurn(emit);emit.notification({method:'item/started',params:{item:{id:'fc1',type:'fileChange',rawDiff:DIFF}}});emit.serverRequest({method:'item/fileChange/requestApproval',params:{itemId:'fc1',threadId:TH,turnId:TU}});finalMsg(emit,nonce());completeTurn(emit);});try{await x.broker.startTask({workspace:wt.linked,instruction:'c'});await x.until(()=>x.events.some(e=>e.type==='proposal-turn-ended'));const ev=x.events.find(e=>e.type==='proposal-turn-ended');assert.equal(ev.outcome,'conflict');const props=x.broker.listPatchProposals();assert.equal(props.length,1);assert.equal(props[0].papersStatus,'conflict');await assert.rejects(()=>x.broker.applyPatchProposal(props[0].proposalId),/already decided/);assert.match(fs.readFileSync(path.join(wt.linked,'a.txt'),'utf8'),/^a\r?\n$/);}finally{await x.cleanup();wt.cleanup();}});
test('valid nonce-bound message becomes an actionable proposal end to end',async()=>{const wt=worktrees();const x=brokerFixture((emit,nonce)=>{stdTurn(emit);finalMsg(emit,nonce());completeTurn(emit);});try{await x.broker.startTask({workspace:wt.linked,instruction:'c'});await x.until(()=>x.broker.listPatchProposals().length===1);const p=x.broker.listPatchProposals()[0];assert.equal(p.proposalSource,'provider-message-json');assert.deepEqual(p.affectedPaths,['a.txt']);const receipt=await x.broker.applyPatchProposal(p.proposalId);assert.equal(receipt.providerDecision,'not-applicable');assert.equal(receipt.outcome,'applied-by-papers');assert.match(fs.readFileSync(path.join(wt.linked,'a.txt'),'utf8'),/^b\r?\n$/);assert.deepEqual(x.broker.listPatchReceipts().length,1);}finally{await x.cleanup();wt.cleanup();}});
