'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {spawnSync}=require('node:child_process');
const {validateUnifiedDiff,normalizePatchPath,assertExistingChainSafe}=require('../../patch/PatchProposalValidator');
const {GitPatchApplier,locks}=require('../../patch/GitPatchApplier');const {PapersPatchController}=require('../../patch/PapersPatchController');const {validateIdentifierOnly}=require('../../codex/protocol/validators');
const MOD=`diff --git a/a.txt b/a.txt\nindex 3367afd..3e75765 100644\n--- a/a.txt\n+++ b/a.txt\n@@ -1 +1 @@\n-old\n+new\n`;
const NEW=`diff --git a/new.txt b/new.txt\nnew file mode 100644\nindex 0000000..ce01362\n--- /dev/null\n+++ b/new.txt\n@@ -0,0 +1 @@\n+hello\n`;
function invalid(body){assert.throws(()=>validateUnifiedDiff(body));}
test('valid one-file text modification',()=>assert.deepEqual(validateUnifiedDiff(MOD).affectedPaths,['a.txt']));
test('valid new text file',()=>assert.deepEqual(validateUnifiedDiff(NEW).affectedPaths,['new.txt']));
test('path traversal rejection',()=>invalid(MOD.replaceAll('a.txt','../a.txt')));
test('absolute Windows path rejection',()=>invalid(MOD.replaceAll('a.txt','C:/a.txt')));
test('UNC path rejection',()=>assert.throws(()=>normalizePatchPath('//server/share/a.txt')));
test('.git path rejection',()=>invalid(MOD.replaceAll('a.txt','.git/config')));
test('sibling-prefix boundary rejection',()=>assert.throws(()=>normalizePatchPath('../ws-other/a')));
test('binary patch rejection',()=>invalid('GIT binary patch\nliteral 1\nA'));
test('rename rejection',()=>invalid(MOD.replace('index 3367afd..3e75765 100644','similarity index 100%\nrename from a.txt\nrename to b.txt')));
test('delete rejection',()=>invalid(MOD.replace('+++ b/a.txt','+++ /dev/null')));
test('mode-change rejection',()=>invalid(MOD.replace('index 3367afd..3e75765 100644','old mode 100644\nnew mode 100755')));
test('malformed patch rejection',()=>invalid('diff --git bad\n@@ nope'));
test('empty patch rejection',()=>invalid(''));
test('duplicate conflicting section rejection',()=>invalid(MOD+MOD));
test('device name rejection',()=>invalid(MOD.replaceAll('a.txt','CON.txt')));
test('alternate data stream rejection',()=>invalid(MOD.replaceAll('a.txt','a.txt:evil')));
test('NUL rejection',()=>invalid(MOD+'\0'));
test('unexpected header rejection',()=>invalid(MOD.replace('index 3367afd..3e75765 100644','totally unsafe header')));
test('renderer raw-diff injection rejection',()=>assert.throws(()=>validateIdentifierOnly({proposalId:'p',rawDiff:MOD})));
test('identifier-only IPC accepts proposal id',()=>assert.deepEqual(validateIdentifierOnly({proposalId:'p'}),{proposalId:'p'}));
test('symlink or reparse escape rejection',t=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'papers-link-'));const outside=fs.mkdtempSync(path.join(os.tmpdir(),'papers-out-'));try{try{fs.symlinkSync(outside,path.join(d,'link'),'junction');}catch{t.skip('junction creation unavailable');return;}assert.throws(()=>assertExistingChainSafe(d,'link/a.txt'));}finally{fs.rmSync(d,{recursive:true,force:true});fs.rmSync(outside,{recursive:true,force:true});}});

function git(cwd,args){const r=spawnSync('git',['-C',cwd,...args],{encoding:'utf8',shell:false});if(r.status!==0)throw new Error(r.stderr);return r.stdout.trim();}
function fixture(){const base=fs.mkdtempSync(path.join(os.tmpdir(),'papers-patch-test-'));const repo=path.join(base,'repo');const wt=path.join(base,'wt');fs.mkdirSync(repo);git(repo,['init']);git(repo,['config','user.email','papers@example.invalid']);git(repo,['config','user.name','Papers Test']);fs.writeFileSync(path.join(repo,'a.txt'),'old\n');git(repo,['add','a.txt']);git(repo,['commit','-m','base']);git(repo,['worktree','add','-b','patch-test',wt]);return{base,repo,wt,cleanup(){try{git(repo,['worktree','remove','--force',wt]);}catch{}fs.rmSync(base,{recursive:true,force:true});}};}
function controllerFor(f,options={}){let controller;const decisions=[];const approvals={submitDecision(id,decision){decisions.push({id,decision});if(options.terminal!==false)setTimeout(()=>controller.observeProviderEvent({params:{item:{id:'item1',status:options.status||'declined'}}}),options.delay||0);}};controller=new PapersPatchController({approvals,declineTimeoutMs:40,...options});const proposal=controller.capture({threadId:'th',turnId:'tu',itemId:'item1',approvalRequestId:7,approvalId:'apr',worktreeRoot:f.wt,repositoryRoot:f.wt,rawDiff:MOD,model:'gpt-5.4-mini'});return{controller,proposal,decisions};}
test('actual valid patch applies only after decline confirmation',async()=>{const f=fixture();try{const{controller,proposal,decisions}=controllerFor(f);const r=await controller.apply(proposal.proposalId);assert.match(fs.readFileSync(path.join(f.wt,'a.txt'),'utf8'),/^new\r?\n$/);assert.deepEqual(decisions,[{id:'apr',decision:'deny'}]);assert.equal(r.providerTerminalStatus,'declined');}finally{f.cleanup();}});
test('no mutation occurs before decline confirmation',async()=>{const f=fixture();try{const x=controllerFor(f,{delay:30});const pending=x.controller.apply(x.proposal.proposalId);assert.match(fs.readFileSync(path.join(f.wt,'a.txt'),'utf8'),/^old\r?\n$/);await pending;assert.match(fs.readFileSync(path.join(f.wt,'a.txt'),'utf8'),/^new\r?\n$/);}finally{f.cleanup();}});
test('provider denial failure prevents application',async()=>{const f=fixture();try{const x=controllerFor(f,{terminal:false});await assert.rejects(()=>x.controller.apply(x.proposal.proposalId),/not confirmed/);assert.match(fs.readFileSync(path.join(f.wt,'a.txt'),'utf8'),/^old\r?\n$/);}finally{f.cleanup();}});
test('conflicting provider terminal fails closed',async()=>{const f=fixture();try{const x=controllerFor(f,{status:'completed'});await assert.rejects(()=>x.controller.apply(x.proposal.proposalId),/did not confirm/);assert.match(fs.readFileSync(path.join(f.wt,'a.txt'),'utf8'),/^old\r?\n$/);}finally{f.cleanup();}});
test('affected-file hash drift prevents application',async()=>{const f=fixture();try{const x=controllerFor(f);fs.writeFileSync(path.join(f.wt,'a.txt'),'drift\n');await assert.rejects(()=>x.controller.apply(x.proposal.proposalId),/clean|changed|drift/i);}finally{f.cleanup();}});
test('dirty worktree rejected at capture',()=>{const f=fixture();try{fs.writeFileSync(path.join(f.wt,'other.txt'),'x');const applier=new GitPatchApplier();assert.throws(()=>applier.inspect(f.wt,['a.txt']),/clean/);}finally{f.cleanup();}});
test('HEAD drift prevents application',async()=>{const f=fixture();try{const x=controllerFor(f);fs.writeFileSync(path.join(f.wt,'b.txt'),'b');git(f.wt,['add','b.txt']);git(f.wt,['commit','-m','drift']);await assert.rejects(()=>x.controller.apply(x.proposal.proposalId),/HEAD|changed|drift/i);}finally{f.cleanup();}});
test('branch drift prevents application',async()=>{const f=fixture();try{const x=controllerFor(f);git(f.wt,['switch','-c','other']);await assert.rejects(()=>x.controller.apply(x.proposal.proposalId),/branch|changed|drift/i);}finally{f.cleanup();}});
test('duplicate apply decision rejected',async()=>{const f=fixture();try{const x=controllerFor(f);await x.controller.apply(x.proposal.proposalId);await assert.rejects(()=>x.controller.apply(x.proposal.proposalId),/already decided/);}finally{f.cleanup();}});
test('unknown proposal rejected',()=>{const f=fixture();try{const x=controllerFor(f);assert.throws(()=>x.controller.get('missing'),/Unknown/);}finally{f.cleanup();}});
test('duplicate provider proposal captured once',()=>{const f=fixture();try{const x=controllerFor(f);const p=x.controller.capture({threadId:'th',turnId:'tu',itemId:'item1',approvalRequestId:8,approvalId:'apr2',worktreeRoot:f.wt,repositoryRoot:f.wt,rawDiff:MOD});assert.equal(p.proposalId,x.proposal.proposalId);assert.equal(x.controller.list().length,1);}finally{f.cleanup();}});
test('receipt records provider denial and Papers application without credentials',async()=>{const f=fixture();try{const x=controllerFor(f);const r=await x.controller.apply(x.proposal.proposalId);assert.equal(r.providerDecision,'decline');assert.equal(r.outcome,'applied-by-papers');assert.doesNotMatch(JSON.stringify(r),/token|Bearer|auth\.json|sk-/i);}finally{f.cleanup();}});
test('new file patch changes only expected path',async()=>{const f=fixture();try{let c;const approvals={submitDecision(){setImmediate(()=>c.observeProviderEvent({params:{item:{id:'item1',status:'declined'}}}));}};c=new PapersPatchController({approvals});const p=c.capture({threadId:'t',turnId:'u',itemId:'item1',approvalRequestId:1,approvalId:'a',worktreeRoot:f.wt,repositoryRoot:f.wt,rawDiff:NEW});await c.apply(p.proposalId);assert.match(fs.readFileSync(path.join(f.wt,'new.txt'),'utf8'),/^hello\r?\n$/);assert.deepEqual(git(f.wt,['status','--porcelain']).split(/\r?\n/),['?? new.txt']);}finally{f.cleanup();}});
test('stale proposal is rejected',async()=>{const f=fixture();try{let x=controllerFor(f,{staleMs:1});await new Promise(r=>setTimeout(r,5));await assert.rejects(()=>x.controller.apply(x.proposal.proposalId),/stale/);}finally{f.cleanup();}});
test('proposal and worktree mismatch rejected',()=>{const f=fixture();try{let c=new PapersPatchController({approvals:{}});assert.throws(()=>c.capture({threadId:'t',turnId:'u',itemId:'i',approvalRequestId:1,approvalId:'a',worktreeRoot:f.wt,repositoryRoot:f.repo,rawDiff:MOD}),/do not match/);}finally{f.cleanup();}});
test('in-process worktree lock rejects concurrent apply',()=>{const f=fixture();try{const x=controllerFor(f);const root=fs.realpathSync.native(f.wt);locks.add(root);assert.throws(()=>x.controller.applier.apply(x.controller.proposals.get(x.proposal.proposalId)),/lock/);locks.delete(root);}finally{f.cleanup();}});
test('conflicting duplicate terminal events fail closed',async()=>{const f=fixture();try{let c;const approvals={submitDecision(){setImmediate(()=>{c.observeProviderEvent({params:{item:{id:'item1',status:'declined'}}});c.observeProviderEvent({params:{item:{id:'item1',status:'completed'}}});});}};c=new PapersPatchController({approvals});const p=c.capture({threadId:'t',turnId:'u',itemId:'item1',approvalRequestId:1,approvalId:'a',worktreeRoot:f.wt,repositoryRoot:f.wt,rawDiff:MOD});await assert.rejects(()=>c.apply(p.proposalId),/conflicting/);assert.match(fs.readFileSync(path.join(f.wt,'a.txt'),'utf8'),/^old\r?\n$/);}finally{f.cleanup();}});
test('submodule boundary rejected',()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'papers-gitlink-'));try{fs.writeFileSync(path.join(d,'.git'),'gitdir: synthetic');const spawn=(_git,args)=>{const op=args.slice(2).join(' ');let stdout='';if(op==='rev-parse --show-toplevel')stdout=d+'\n';else if(op==='rev-parse --git-dir')stdout='.git\n';else if(op==='branch --show-current')stdout='x\n';else if(op==='rev-parse HEAD')stdout='a'.repeat(40)+'\n';else if(op.startsWith('ls-files --stage'))stdout='160000 '+('b'.repeat(40))+' 0\tsub\n';return{status:0,stdout,stderr:''};};assert.throws(()=>new GitPatchApplier({spawn}).inspect(d,['sub/file.txt']),/submodule/);}finally{fs.rmSync(d,{recursive:true,force:true});}});
