'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {spawnSync}=require('node:child_process');
const {PapersPatchController}=require('../../patch/PapersPatchController');
const {isTruthfulReceipt,receiptRows,applyResolution,createReceiptLedger}=require('../../ui/patch-receipt-view');
const MOD=`diff --git a/a.txt b/a.txt\nindex 3367afd..3e75765 100644\n--- a/a.txt\n+++ b/a.txt\n@@ -1 +1 @@\n-old\n+new\n`;
function git(cwd,args){const r=spawnSync('git',['-C',cwd,...args],{encoding:'utf8',shell:false});if(r.status!==0)throw new Error(r.stderr);return r.stdout.trim();}
function fixture(){const base=fs.mkdtempSync(path.join(os.tmpdir(),'papers-receipt-test-'));const repo=path.join(base,'repo');const wt=path.join(base,'wt');fs.mkdirSync(repo);git(repo,['init']);git(repo,['config','user.email','papers@example.invalid']);git(repo,['config','user.name','Papers Test']);fs.writeFileSync(path.join(repo,'a.txt'),'old\n');git(repo,['add','a.txt']);git(repo,['commit','-m','base']);git(repo,['worktree','add','-b','receipt-test',wt]);return{base,repo,wt,cleanup(){try{git(repo,['worktree','remove','--force',wt]);}catch{}fs.rmSync(base,{recursive:true,force:true});}};}
async function appliedReceipt(f){let c;const approvals={submitDecision(){setImmediate(()=>c.observeProviderEvent({params:{item:{id:'item1',status:'declined'}}}));}};c=new PapersPatchController({approvals});const p=c.capture({threadId:'th',turnId:'tu',itemId:'item1',approvalRequestId:7,approvalId:'apr',worktreeRoot:f.wt,repositoryRoot:f.wt,rawDiff:MOD,model:'gpt-5.4-mini'});return c.apply(p.proposalId);}
test('successful apply result contains a truthful receipt',async()=>{const f=fixture();try{const r=await appliedReceipt(f);assert.ok(isTruthfulReceipt(r));assert.equal(applyResolution({ok:true,value:r}).state,'applied');}finally{f.cleanup();}});
test('receipt outcome must be applied-by-papers',async()=>{const f=fixture();try{const r=await appliedReceipt(f);assert.equal(r.outcome,'applied-by-papers');assert.equal(isTruthfulReceipt({...r,outcome:'applied'}),false);assert.equal(applyResolution({ok:true,value:{...r,outcome:'applied'}}).state,'failed');}finally{f.cleanup();}});
test('receipt provider decision is decline',async()=>{const f=fixture();try{const r=await appliedReceipt(f);assert.equal(r.providerDecision,'decline');assert.equal(isTruthfulReceipt({...r,providerDecision:'approve'}),false);}finally{f.cleanup();}});
test('receipt retains provider terminal status',async()=>{const f=fixture();try{const r=await appliedReceipt(f);assert.equal(r.providerTerminalStatus,'declined');const rows=Object.fromEntries(receiptRows(r));assert.equal(rows['Provider terminal status'],'declined');assert.equal(isTruthfulReceipt({...r,providerTerminalStatus:''}),false);}finally{f.cleanup();}});
test('duplicate return/event receipt is deduplicated by receiptId',async()=>{const f=fixture();try{const r=await appliedReceipt(f);const ledger=createReceiptLedger();assert.equal(ledger.register(r),true);assert.equal(ledger.register(r),false);assert.equal(ledger.register(JSON.parse(JSON.stringify(r))),false);assert.equal(ledger.register({...r,receiptId:'pr_other'}),true);}finally{f.cleanup();}});
test('malformed or absent receipt cannot produce applied-success state',async()=>{const f=fixture();try{const r=await appliedReceipt(f);assert.equal(applyResolution({ok:true}).state,'failed');assert.equal(applyResolution({ok:true,value:null}).state,'failed');assert.equal(applyResolution({ok:true,value:'applied-by-papers'}).state,'failed');assert.equal(applyResolution({ok:false,error:{message:'x'}}).state,'failed');assert.equal(applyResolution(null).state,'failed');for(const k of['receiptId','providerTerminalStatus','branch','headBefore','patchSHA256','resultingDiffSHA256','startedAt','completedAt'])assert.equal(applyResolution({ok:true,value:{...r,[k]:''}}).state,'failed',k);assert.equal(applyResolution({ok:true,value:{...r,affectedPaths:[]}}).state,'failed');const ledger=createReceiptLedger();assert.equal(ledger.register({...r,outcome:'failed'}),false);}finally{f.cleanup();}});
test('receipt rendering excludes sensitive fields',async()=>{const f=fixture();try{const r=await appliedReceipt(f);const tainted={...r,access_token:'sekret-123456',authJsonPath:'C:/Users/x/.codex/auth.json',HOME:'C:/Users/x',authorization:'Bearer abcdef'};const rows=receiptRows(tainted);const labels=rows.map(([k])=>k);assert.deepEqual(labels,['Outcome','Provider decision','Provider terminal status','Affected files','Branch','HEAD before','Patch SHA-256','Resulting diff SHA-256','Started','Completed']);const flat=JSON.stringify(rows);assert.doesNotMatch(flat,/sekret|Bearer|auth\.json|Users/i);assert.doesNotMatch(flat,/preApplyHashes|postApplyHashes|worktreeRoot/);assert.equal(rows.find(([k])=>k==='Affected files')[1],'a.txt');}finally{f.cleanup();}});
