'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const os=require('node:os');const fs=require('node:fs');const path=require('node:path');
const {resolveCodexExecutable}=require('../../codex/CodexExecutableResolver');
const {CodexAuthManager}=require('../../codex/CodexAuthManager');
const {AppServerTransport}=require('../../codex/AppServerTransport');

// A virtual Windows filesystem: only listed files/dirs exist. Simulates the
// real deadline blocker: npm codex.cmd shim on PATH, no codex.exe on PATH,
// native binary vendored inside the npm package.
const NPM=path.join('vroot','npm');
const SHIM=path.join(NPM,'codex');
const VENDORED=path.join(NPM,'node_modules','@openai','codex','node_modules','@openai','codex-win32-x64','vendor','x86_64-pc-windows-msvc','codex','codex.exe');
function vfs(files,dirs){return{statSync(p){if(files.includes(p))return{isFile:()=>true};if((dirs||[]).some(d=>d.dir===p))return{isFile:()=>false};const e=new Error('ENOENT');e.code='ENOENT';throw e;},readdirSync(p){const d=(dirs||[]).find(x=>x.dir===p);if(!d){const e=new Error('ENOENT');e.code='ENOENT';throw e;}return d.entries;}};}
function shimWorld(){return{io:vfs([SHIM,path.join(NPM,'codex.cmd'),VENDORED],[{dir:path.join(NPM,'node_modules','@openai','codex','node_modules','@openai'),entries:['codex-win32-x64']},{dir:path.join(NPM,'node_modules','@openai','codex','node_modules','@openai','codex-win32-x64','vendor'),entries:['x86_64-pc-windows-msvc']}]),runWhere:(name)=>name==='codex'?[SHIM,path.join(NPM,'codex.cmd')]:[]};}

test('codex.cmd shim on PATH without codex.exe resolves the vendored native binary',()=>{const w=shimWorld();const r=resolveCodexExecutable({env:{},platform:'win32',io:w.io,runWhere:w.runWhere});assert.equal(r.path,VENDORED);assert.equal(r.source,'npm-shim-vendor');});
test('PAPERS_CODEX_EXE naming an existing regular exe wins',()=>{const exe=path.join('vroot','custom','codex.exe');const r=resolveCodexExecutable({env:{PAPERS_CODEX_EXE:exe},platform:'win32',io:vfs([exe]),runWhere:()=>[]});assert.equal(r.source,'env-override');assert.equal(r.path,path.resolve(exe));});
test('PAPERS_CODEX_EXE naming a .cmd shim is not accepted and falls through',()=>{const w=shimWorld();const r=resolveCodexExecutable({env:{PAPERS_CODEX_EXE:path.join(NPM,'codex.cmd')},platform:'win32',io:w.io,runWhere:w.runWhere});assert.equal(r.source,'npm-shim-vendor');});
test('PAPERS_CODEX_EXE naming a missing file falls through to candidates',()=>{const w=shimWorld();const r=resolveCodexExecutable({env:{PAPERS_CODEX_EXE:path.join('vroot','gone.exe')},platform:'win32',io:w.io,runWhere:w.runWhere});assert.equal(r.path,VENDORED);});
test('native codex.exe directly on PATH is preferred over shim vendoring',()=>{const exe=path.join('vroot','bin','codex.exe');const w=shimWorld();const r=resolveCodexExecutable({env:{},platform:'win32',io:vfs([exe,SHIM,VENDORED]),runWhere:(n)=>n==='codex.exe'?[exe]:[SHIM]});assert.equal(r.path,exe);assert.equal(r.source,'path-native');});
test('nothing resolvable is a specific sanitized CODEX_EXECUTABLE_NOT_FOUND',()=>{try{resolveCodexExecutable({env:{},platform:'win32',io:vfs([]),runWhere:()=>[]});assert.fail('should throw');}catch(err){assert.equal(err.code,'CODEX_EXECUTABLE_NOT_FOUND');assert.match(err.message,/PAPERS_CODEX_EXE/);assert.doesNotMatch(err.message,new RegExp(os.homedir().replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'));assert.doesNotMatch(err.message,/vroot|AppData/i);}});

function notFoundResolver(){const{CodexError,CODE}=require('../../codex/CodexErrors');return()=>{throw new CodexError(CODE.CODEX_EXECUTABLE_NOT_FOUND,'The native Codex executable was not found. Install the Codex CLI, or set PAPERS_CODEX_EXE to the full path of the native codex executable.');};}
test('auth status reports CODEX_EXECUTABLE_NOT_FOUND, not generic failed',async()=>{const m=new CodexAuthManager({codexExecutable:'codex.exe',codexHome:'h'},{CODEX_HOME:'h'},{resolveExecutable:notFoundResolver()});const r=await m.getStatus();assert.equal(r.state,'failed');assert.equal(r.reason,'CODEX_EXECUTABLE_NOT_FOUND');assert.match(r.message,/PAPERS_CODEX_EXE/);});
test('begin authentication without a native executable fails specifically and copies nothing',async()=>{const m=new CodexAuthManager({codexExecutable:'codex.exe',codexHome:'h'},{CODEX_HOME:'h'},{resolveExecutable:notFoundResolver()});const r=await m.beginAuthentication();assert.equal(r.state,'failed');assert.equal(r.reason,'CODEX_EXECUTABLE_NOT_FOUND');assert.equal('command' in r,false);});
test('login command and status use the resolved native executable',async()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'papers-exe-'));const native=path.join(d,'codex.exe');fs.writeFileSync(native,'');try{const spawned=[];const fakeSpawn=(exe)=>{spawned.push(exe);const{EventEmitter}=require('node:events');const c=new EventEmitter();c.stdout=new EventEmitter();c.stderr=new EventEmitter();c.kill=()=>{};setImmediate(()=>{c.stdout.emit('data','logged in');c.emit('close',0);});return c;};const m=new CodexAuthManager({codexExecutable:'codex.exe',codexHome:'h'},{CODEX_HOME:'h'},{spawn:fakeSpawn,resolveExecutable:()=>({path:native,source:'npm-shim-vendor'})});const b=await m.beginAuthentication();assert.match(b.command,/login --device-auth$/);assert.ok(b.command.includes(native));assert.match(b.command,/New-Item -ItemType Directory -Force -Path \$env:CODEX_HOME/);const s=await m.getStatus();assert.equal(s.state,'authenticated');assert.deepEqual(spawned,[native]);}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('App Server startup without a native executable fails with the specific code and spawns nothing',()=>{const t=new AppServerTransport({codexExecutable:'codex.exe'},{CODEX_HOME:'h'},{resolveExecutable:notFoundResolver()});assert.throws(()=>t.start(),(err)=>err.code==='CODEX_EXECUTABLE_NOT_FOUND');assert.equal(t.child,null);});
