'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {EventEmitter}=require('node:events');const {spawnSync}=require('node:child_process');
const {CodexRuntimeBroker}=require('../../codex/CodexRuntimeBroker');const {CodexAuthManager}=require('../../codex/CodexAuthManager');const {FakeAppServer}=require('../../codex/testing/FakeAppServer');const {registerCodexIpc}=require('../../codex/ipc');const {GitPatchApplier}=require('../../patch/GitPatchApplier');
function authFactory(state='authenticated',capture){return(_cfg,env)=>{if(capture)capture.env=env;return{getStatus:async()=>({state}),beginAuthentication:async()=>({state:'authenticating',command:"$env:CODEX_HOME='papers'; & 'codex.exe' login --device-auth"}),logout:async()=>({state:'unauthenticated'})};};}
function brokerFixture(script={},opts={}){const userDataDir=fs.mkdtempSync(path.join(os.tmpdir(),'papers-launch-'));let fake;let starts=0;const broker=new CodexRuntimeBroker({userDataDir,env:{},authFactory:opts.authFactory||authFactory(),transportFactory:()=>{fake=new FakeAppServer({...script,codexHome:path.join(userDataDir,'codex-home')});const start=fake.start.bind(fake);fake.start=()=>{starts++;return start();};return fake;}});return{broker,getFake:()=>fake,starts:()=>starts,cleanup:async()=>{try{await broker.stop();}catch{}fs.rmSync(userDataDir,{recursive:true,force:true});}};}
test('startTask from stopped starts the broker once',async()=>{const f=brokerFixture();try{await f.broker.startTask({workspace:'D:\\ws',instruction:'x'});assert.equal(f.starts(),1);assert.equal(f.broker.machine.snapshot(),'running');}finally{await f.cleanup();}});
test('concurrent startup callers share one startup promise',async()=>{const f=brokerFixture();try{const a=f.broker.ensureStarted();const b=f.broker.ensureStarted();assert.strictEqual(f.broker._startPromise!==null,true);await Promise.all([a,b]);assert.equal(f.starts(),1);}finally{await f.cleanup();}});
test('runtime is ready before thread start',async()=>{let seen;const f=brokerFixture({onRequest:(method)=>{if(method==='thread/start')seen=f.broker.machine.snapshot();}});try{await f.broker.startTask({workspace:'D:\\ws',instruction:'x'});assert.equal(seen,'ready');}finally{await f.cleanup();}});
test('startup failure surfaces and failed startup retries without overlap',async()=>{const userDataDir=fs.mkdtempSync(path.join(os.tmpdir(),'papers-retry-'));let attempt=0;const broker=new CodexRuntimeBroker({userDataDir,env:{},authFactory:authFactory(),transportFactory:()=>{attempt++;const fake=new FakeAppServer({codexHome:path.join(userDataDir,'codex-home')});if(attempt===1){const request=fake.request.bind(fake);fake.request=async(method,params)=>{if(method==='initialize')throw new Error('startup boom');return request(method,params);};}return fake;}});try{await assert.rejects(()=>broker.ensureStarted(),/startup boom/);assert.equal(broker.machine.snapshot(),'failed');await broker.ensureStarted();assert.equal(attempt,2);assert.equal(broker.machine.snapshot(),'ready');}finally{await broker.stop();fs.rmSync(userDataDir,{recursive:true,force:true});}});
test('ready runtime is not restarted',async()=>{const f=brokerFixture();try{await f.broker.ensureStarted();await f.broker.ensureStarted();assert.equal(f.starts(),1);}finally{await f.cleanup();}});
test('active runtime rejects a second task',async()=>{const f=brokerFixture();try{await f.broker.startTask({workspace:'D:\\ws',instruction:'one'});await assert.rejects(()=>f.broker.startTask({workspace:'D:\\ws',instruction:'two'}),/already active/);assert.equal(f.starts(),1);}finally{await f.cleanup();}});
test('duplicate start clicks launch one App Server and one turn',async()=>{let turns=0;const f=brokerFixture({onRequest:(m)=>{if(m==='turn/start')turns++;}});try{const one=f.broker.startTask({workspace:'D:\\ws',instruction:'one'});await assert.rejects(()=>f.broker.startTask({workspace:'D:\\ws',instruction:'two'}),/already active/);await one;assert.equal(f.starts(),1);assert.equal(turns,1);}finally{await f.cleanup();}});
test('auth status creates isolated context without App Server startup',async()=>{const capture={};const f=brokerFixture({}, {authFactory:authFactory('authenticated',capture)});try{assert.equal((await f.broker.getAuthStatus()).state,'authenticated');assert.equal(f.starts(),0);assert.equal(capture.env.CODEX_HOME,path.join(f.broker.config.codexHome));}finally{await f.cleanup();}});
test('auth context never targets global home',async()=>{const capture={};const f=brokerFixture({}, {authFactory:authFactory('authenticated',capture)});try{await f.broker.getAuthStatus();assert.notEqual(path.resolve(capture.env.CODEX_HOME).toLowerCase(),path.resolve(os.homedir(),'.codex').toLowerCase());}finally{await f.cleanup();}});
test('fixed login command contains only configured Papers home and device auth',async()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),"papers'auth-"));const exe=path.join(d,'codex.exe');fs.writeFileSync(exe,'');const home=path.join(d,"paper's-home");const manager=new CodexAuthManager({codexExecutable:exe,codexHome:home},{CODEX_HOME:home});try{const r=await manager.beginAuthentication();assert.equal(r.state,'authenticating');assert.match(r.command,/login --device-auth$/);assert.match(r.command,/paper''s-home/);assert.doesNotMatch(r.command,new RegExp(os.homedir().replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));}finally{fs.rmSync(d,{recursive:true,force:true});}});
test('login preparation is not journaled',async()=>{const f=brokerFixture();try{await f.broker.beginAuth();assert.equal(f.broker.journal.recent(20).length,0);}finally{await f.cleanup();}});
function git(cwd,args){const r=spawnSync('git',['-C',cwd,...args],{encoding:'utf8',shell:false});if(r.status)throw new Error(r.stderr);return r.stdout.trim();}
function worktrees(){const base=fs.mkdtempSync(path.join(os.tmpdir(),'papers-picker-'));const repo=path.join(base,'repo');const linked=path.join(base,'linked');fs.mkdirSync(repo);git(repo,['init']);git(repo,['config','user.email','papers@example.invalid']);git(repo,['config','user.name','Papers Test']);fs.writeFileSync(path.join(repo,'a.txt'),'a\n');git(repo,['add','.']);git(repo,['commit','-m','base']);git(repo,['worktree','add','-b','creator-task',linked]);return{base,repo,linked,cleanup(){try{git(repo,['worktree','remove','--force',linked]);}catch{}fs.rmSync(base,{recursive:true,force:true});}};}
function ipcHarness({broker,dialog,clipboard,workspaceInspector,implementationRoot}={}){const handlers=new Map();const ipcMain={handle:(n,h)=>handlers.set(n,h)};broker=broker||Object.assign(new EventEmitter(),{getRuntimeStatus:()=>({state:'stopped'}),getAuthStatus:async()=>({state:'authenticated'}),beginAuth:async()=>({state:'authenticating',command:'fixed'}),startTask:async(i)=>i});registerCodexIpc(ipcMain,()=>null,{broker,dialog,clipboard,workspaceInspector,implementationRoot});return{broker,invoke:(name,raw)=>handlers.get(name)(null,raw)};}
test('workspace picker cancellation is safe',async()=>{const h=ipcHarness({dialog:{showOpenDialog:async()=>({canceled:true,filePaths:[]})}});const r=await h.invoke('codex:chooseWorkspace');assert.equal(r.ok,true);assert.equal(r.value.canceled,true);});
test('ordinary clone with .git directory is rejected',async()=>{const f=worktrees();try{const h=ipcHarness({dialog:{showOpenDialog:async()=>({canceled:false,filePaths:[f.repo]})}});const r=await h.invoke('codex:chooseWorkspace');assert.equal(r.ok,false);}finally{f.cleanup();}});
test('dirty linked worktree is rejected',async()=>{const f=worktrees();try{fs.writeFileSync(path.join(f.linked,'dirty.txt'),'x');const h=ipcHarness({dialog:{showOpenDialog:async()=>({canceled:false,filePaths:[f.linked]})}});const r=await h.invoke('codex:chooseWorkspace');assert.equal(r.ok,false);}finally{f.cleanup();}});
test('clean disposable linked worktree is accepted',async()=>{const f=worktrees();try{const h=ipcHarness({dialog:{showOpenDialog:async()=>({canceled:false,filePaths:[f.linked]})}});const r=await h.invoke('codex:chooseWorkspace');assert.equal(r.ok,true);assert.equal(r.value.validation,'passed');assert.equal(r.value.workspace,fs.realpathSync.native(f.linked));}finally{f.cleanup();}});
test('protected implementation worktree selection is rejected',async()=>{const root=path.resolve(__dirname,'../../..');const h=ipcHarness({dialog:{showOpenDialog:async()=>({canceled:false,filePaths:[root]})},implementationRoot:root});const r=await h.invoke('codex:chooseWorkspace');assert.equal(r.ok,false);});
test('renderer cannot submit a free-text workspace',async()=>{const h=ipcHarness();const r=await h.invoke('codex:startTask',{workspace:'D:\\typed',instruction:'x',requireOffline:false});assert.equal(r.ok,false);assert.equal(r.error.code,'IPC_REJECTED');});
test('unknown task launch fields are rejected',async()=>{const h=ipcHarness();const r=await h.invoke('codex:startTask',{workspace:'D:\\typed',instruction:'x',requireOffline:false,model:'other'});assert.equal(r.ok,false);assert.equal(r.error.code,'IPC_REJECTED');});
test('login IPC accepts no renderer arguments and copies fixed command',async()=>{let calls=0;const broker=Object.assign(new EventEmitter(),{beginAuth:async()=>{calls++;return{state:'authenticating',command:'fixed-command'};},getRuntimeStatus:()=>({state:'stopped'})});let copied;const h=ipcHarness({broker,clipboard:{writeText:v=>{copied=v;}}});assert.equal((await h.invoke('codex:beginAuth',{})).ok,false);const r=await h.invoke('codex:beginAuth');assert.equal(r.value.copied,true);assert.equal(copied,'fixed-command');assert.equal(calls,1);assert.equal('command' in r.value,false);});
test('trusted picker workspace is passed unchanged and auth is rechecked',async()=>{let started;const broker=Object.assign(new EventEmitter(),{getRuntimeStatus:()=>({state:'stopped'}),getAuthStatus:async()=>({state:'authenticated'}),startTask:async i=>{started=i;return i;}});const inspector={inspect:()=>({worktreeRoot:'D:\\trusted',branch:'b',head:'h'})};const h=ipcHarness({broker,workspaceInspector:inspector,dialog:{showOpenDialog:async()=>({canceled:false,filePaths:['ignored']})}});await h.invoke('codex:chooseWorkspace');const r=await h.invoke('codex:startTask',{workspace:'D:\\trusted',instruction:'x',requireOffline:false});assert.equal(r.ok,true);assert.equal(started.workspace,'D:\\trusted');});
test('no task begins before authentication is confirmed',async()=>{let starts=0;const broker=Object.assign(new EventEmitter(),{getRuntimeStatus:()=>({state:'stopped'}),getAuthStatus:async()=>({state:'unauthenticated'}),startTask:async()=>{starts++;}});const h=ipcHarness({broker,workspaceInspector:{inspect:()=>({worktreeRoot:'D:\\trusted',branch:'b',head:'h'})},dialog:{showOpenDialog:async()=>({canceled:false,filePaths:['ignored']})}});await h.invoke('codex:chooseWorkspace');const r=await h.invoke('codex:startTask',{workspace:'D:\\trusted',instruction:'x',requireOffline:false});assert.equal(r.ok,false);assert.equal(r.error.code,'AUTH_REQUIRED');assert.equal(starts,0);});
test('fresh task reaches existing structured proposal capture path',async()=>{const wt=worktrees();const diff=`diff --git a/a.txt b/a.txt\nindex 7898192..6178079 100644\n--- a/a.txt\n+++ b/a.txt\n@@ -1 +1 @@\n-a\n+b\n`;const f=brokerFixture({afterTurnStart(emit){emit.notification({method:'turn/started',params:{turn:{id:'tu'}}});emit.notification({method:'item/started',params:{item:{id:'i',type:'fileChange',rawDiff:diff}}});emit.serverRequest({method:'item/fileChange/requestApproval',params:{itemId:'i',threadId:'th_fake_1',turnId:'tu'}});}});try{await f.broker.startTask({workspace:wt.linked,instruction:'change'});for(let i=0;i<100&&!f.broker.listPatchProposals().length;i++)await new Promise(r=>setTimeout(r,5));assert.equal(f.broker.listPatchProposals().length,1);}finally{await f.cleanup();wt.cleanup();}});
